[autoexec]
MOUNT C .
C:
ECHO.
ECHO ======================================================
ECHO CNB - Data File Converter
ECHO ======================================================
ECHO.
ECHO ROOT: File converter
ECHO   Edit: edit_cnb.bat
ECHO.
ECHO.
ECHO ======================================================
ECHO Type a command name to run or edit batch file to modify
ECHO ======================================================
ECHO.
