[autoexec]
MOUNT C .
C:
ECHO.
ECHO ======================================================
ECHO HBS - Home Business System
ECHO ======================================================
ECHO.
ECHO AC: Accounting
ECHO   Edit: AC/edit_ac.bat
ECHO.
ECHO.
ECHO ======================================================
ECHO Type a command name to run or edit batch file to modify
ECHO ======================================================
ECHO.
