[autoexec]
MOUNT C .
C:
ECHO.
ECHO ======================================================
ECHO PFC - Processed Foods ERP - Complete multi-module system
ECHO ======================================================
ECHO.
ECHO AP: Accounts Payable
ECHO   Edit: edit_ap.bat
ECHO.
ECHO AR: Accounts Receivable
ECHO   Edit: edit_arp.bat
ECHO.
ECHO FS: Financial Statements
ECHO   Edit: edit_fs.bat
ECHO.
ECHO GL: General Ledger
ECHO   Edit: edit_gl.bat
ECHO.
ECHO IN: Inventory (Job/Product)
ECHO   Edit: edit_inj.bat
ECHO   Edit: edit_pup.bat
ECHO.
ECHO OE: Order Entry
ECHO   Edit: edit_oep.bat
ECHO.
ECHO PR: Payroll
ECHO   Edit: edit_pr.bat
ECHO.
ECHO TS: Time Sheet
ECHO   Edit: edit_ts.bat
ECHO.
ECHO.
ECHO ======================================================
ECHO Type a command name to run or edit batch file to modify
ECHO ======================================================
ECHO.
