[autoexec]
MOUNT C .
C:
ECHO.
ECHO ======================================================
ECHO RDL - Dental Lab Billing
ECHO ======================================================
ECHO.
ECHO AR: Accounts Receivable
ECHO   Edit: AR/edit_arp.bat
ECHO.
ECHO.
ECHO ======================================================
ECHO Type a command name to run or edit batch file to modify
ECHO ======================================================
ECHO.
