[autoexec]
MOUNT C .
C:
ECHO.
ECHO ======================================================
ECHO MPC - McKenry Produce - Accounts Receivable & Payroll System
ECHO ======================================================
ECHO.
ECHO AR: AR (multiple modes)
ECHO   Run:  ARP.EXE
ECHO   Run:  ARD.EXE
ECHO   Run:  ARI.EXE
ECHO   Run:  ARR.EXE
ECHO   Run:  ART.EXE
ECHO   Edit: SYSTEM/edit_arp.bat
ECHO.
ECHO MAIN: Main menu system
ECHO   Run:  MPC.EXE
ECHO   Edit: SYSTEM/edit_mpc.bat
ECHO.
ECHO UTIL: Utilities
ECHO   Run:  IC.EXE
ECHO   Run:  TIMECARD.EXE
ECHO.
ECHO.
ECHO ======================================================
ECHO Type a command name to run or edit batch file to modify
ECHO ======================================================
ECHO.
