[autoexec]
MOUNT C .
C:
ECHO.
ECHO ======================================================
ECHO MCS - McKenry Accounting (AR + GL)
ECHO ======================================================
ECHO.
ECHO AC: Accounting
ECHO   Edit: AC/edit_ac.bat
ECHO.
ECHO.
ECHO ======================================================
ECHO Type a command name to run or edit batch file to modify
ECHO ======================================================
ECHO.
